### ISSUE TITLE
[오타수정] Grid 2.3. min-max 함수

### ISSUE THREAD

**Issue by yeodahui** [flexandgrid/kr.flexandgrid#46]
## 원문
**minmax(auto, max-content를** 사용하면 그리드 아이템 콘텐츠 크기에 맞추어 영역이 설정된다.
![image](https://user-images.githubusercontent.com/102221305/172994198-3c4614b7-8dff-4c59-bfca-17dd80b12461.png)
[🔗Link](https://flexngrid.com/grid/#2.3.%20min-max%20%ED%95%A8%EC%88%98)

## 오타수정
minmax(auto, max-content)를 사용하면 그리드 아이템 콘텐츠 크기에 맞추어 영역이 설정된다.

## 이슈
글을 보다가 작은 오타를 발견해 이슈 남깁니다!

**Comment by mmcho122** [comment]
네 수정했습니다~
